# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.12.3
  -   repo: https://github.com/pycqa/flake8
      rev: 7.0.0
      hooks:
        - id: flake8
          language_version: python3.12.3
