services:
  etweb:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - etdb
    env_file:
      - .env

  etdb:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5455:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=etdata

volumes:
    postgres_data:
