services:
  etweb:
    build: .
    ports:
      - 9898:9898
    volumes:
      - .:/app
    depends_on:
      - etdb
    environment:
      - DEBUG=True
      - DB_HOST=etdb
      - DB_NAME=etdata
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - MIN_PASSWORD_LENGTH=3

  etdb:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5455:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=etdata

volumes:
    postgres_data:
