[tool.black]
py36 = true
include = '\.pyi?$'
exclude = '''
    /(
        \.git
      | \.idea
      | \.hg
      | \.mypy_cache
      | \.tox
      | \.venv
      | _build
      | buck-out
      | build
      | dist
      | blib2to3
      | tests/data
    )/
'''
