# Generated by Django 5.0.6 on 2024-05-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_task_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deleted',
            field=models.BooleanField(db_comment='Whether the task is deleted', default=False),
        ),
    ]
