# Generated by Django 5.0.6 on 2024-05-26 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_task_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_comment='Name of the city', max_length=255)),
                ('country', models.CharField(db_comment='Name of the country', max_length=255)),
                ('latitude', models.FloatField(db_comment='Latitude of the location')),
                ('longitude', models.FloatField(db_comment='Longitude of the location')),
            ],
        ),
    ]
