# Generated by Django 5.0.6 on 2024-05-27 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_task_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(db_comment='Temperature in Kelvin')),
                ('humidity', models.IntegerField(db_comment='Humidity in percent')),
                ('condition', models.IntegerField(db_comment='Weather condition code', default=0)),
                ('latitude', models.FloatField(db_comment='Latitude of the location', default=0)),
                ('longitude', models.FloatField(db_comment='Longitude of the location', default=0)),
                ('created', models.DateTimeField(auto_now_add=True, db_comment='Date and time the task was created')),
                ('updated', models.DateTimeField(auto_now=True, db_comment='Date and time the task was last updated')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='weather',
            field=models.ForeignKey(blank=True, db_comment='Weather for the task', null=True, on_delete=django.db.models.deletion.CASCADE, to='todos.weather'),
        ),
    ]
